version: "1"

services:
  ndc-nginx:
    image: nginx:1.21.5-alpine
    restart: always
    ports:
      - "0.0.0.0:80:80"
    depends_on:
      - ndc-mariadb
      - ndc-redis
      - ndc-spring
    volumes:
      - ./deploy/proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./deploy/proxy/default.conf:/etc/nginx/conf.d/default.conf
      - ../front/build:/usr/share/nginx/html
    networks:
      - ndc_network

  ndc-redis:
    image: redis:4.0-alpine
    restart: always
    volumes:
      - ./deploy/data/redis:/data
    networks:
      - ndc_network

  ndc-mariadb:
    image: mariadb:10
    volumes:
      - ./deploy/db/conf.d:/etc/mysql/conf.d
      - ./deploy/db/data:/var/lib/mysql
      - ./deploy/db/initdb:/docker-entrypoint-initdb.d
    env_file: ./deploy/db/.env
    environment:
      TZ: Asia/Seoul
    restart: always
    networks:
      - ndc_network

  ndc-spring:
    image: ndc-spring:latest
    restart: always
    depends_on:
      - ndc-redis
      - ndc-mariadb
    networks:
      - ndc_network

networks:
  ndc_network:
    driver: bridge
